DROP SCHEMA IF EXISTS accounting;
CREATE SCHEMA IF NOT EXISTS logistics;

CREATE TABLE IF NOT EXISTS logistics.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) ,
    password VARCHAR(255) ,
    username VARCHAR(255) ,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
    );


CREATE TABLE IF NOT EXISTS logistics.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR(20) ,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS logistics.user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    FOREIGN KEY (user_id)
    REFERENCES logistics.users (id),
    FOREIGN KEY (role_id)
    REFERENCES logistics.roles (id)

    );

CREATE TABLE IF NOT EXISTS logistics.warehouses
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    type integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    CONSTRAINT warehouses_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS logistics.products
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ,
    name VARCHAR(100)  NOT NULL,
    description VARCHAR(100) ,
    price NUMERIC(10,4) NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    CONSTRAINT products_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS logistics.customers
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ,
    name VARCHAR(50)  NOT NULL,
    phone VARCHAR(8)  NOT NULL,
    address VARCHAR(100)  NOT NULL,
    email VARCHAR(100)  NOT NULL,
    active boolean DEFAULT true,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS logistics.services
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR(50)  NOT NULL,
    description VARCHAR(100) ,
    CONSTRAINT services_pkey PRIMARY KEY (id)
    );


CREATE TABLE IF NOT EXISTS logistics.deliveries
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ,
    customer_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    deliverie_date timestamp with time zone NOT NULL,
    warehouse_id bigint NOT NULL,
    discount numeric(10,4) NOT NULL,
    total numeric(10,4) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tracking_number VARCHAR(100)  NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    transport_number VARCHAR(10) NOT NULL,
    service_id bigint NOT NULL,
    CONSTRAINT deliveries_pkey PRIMARY KEY (id),
    FOREIGN KEY (customer_id)
    REFERENCES logistics.customers (id),
    FOREIGN KEY (product_id)
    REFERENCES logistics.products (id),
    FOREIGN KEY (warehouse_id)
    REFERENCES logistics.warehouses (id),
    FOREIGN KEY (service_id)
    REFERENCES logistics.services (id)
    );

